export interface ProjectFile {
  path: string;
  name: string;
  category: 'build' | 'source' | 'test' | 'docker' | 'ci' | 'doc';
  language: string;
  description: string;
  content: string;
}

export const PROJECT_FILES: ProjectFile[] = [
  {
    path: 'build.gradle',
    name: 'build.gradle',
    category: 'build',
    language: 'groovy',
    description: 'Gradle build configuration defining Java toolchain, Spring Boot 3.3.4 plugins, and dependencies.',
    content: `plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.devops'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot Web Starter for REST API endpoints
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Spring Boot Actuator for health checks and operational metrics
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Testing dependencies: JUnit 5, AssertJ, Mockito, Spring Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}

bootJar {
    archiveBaseName = 'java-gradle-devops'
    archiveVersion = '1.0.0'
}

jar {
    enabled = false // Disable plain jar in favor of executable bootJar
}`
  },
  {
    path: 'settings.gradle',
    name: 'settings.gradle',
    category: 'build',
    language: 'groovy',
    description: 'Defines the project root name for Gradle multi-project coordination.',
    content: `rootProject.name = 'java-gradle-devops'`
  },
  {
    path: 'gradle/wrapper/gradle-wrapper.properties',
    name: 'gradle-wrapper.properties',
    category: 'build',
    language: 'properties',
    description: 'Specifies the official Gradle distribution URL and caching paths for reproducible builds.',
    content: `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists`
  },
  {
    path: 'gradlew',
    name: 'gradlew',
    category: 'build',
    language: 'bash',
    description: 'POSIX shell script for invoking Gradle wrapper on Linux/macOS.',
    content: `#!/bin/sh
# Gradle start up script for POSIX generated by Gradle Wrapper
APP_HOME="$(cd "\$(dirname "\$0")" && pwd)"
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"`
  },
  {
    path: 'gradlew.bat',
    name: 'gradlew.bat',
    category: 'build',
    language: 'batch',
    description: 'Batch execution script for invoking Gradle wrapper on Windows systems.',
    content: `@if "%DEBUG%" == "" @echo off
@rem Gradle startup script for Windows
set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_HOME=%DIRNAME%
set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar
java -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*`
  },
  {
    path: 'src/main/java/com/devops/app/Application.java',
    name: 'Application.java',
    category: 'source',
    language: 'java',
    description: 'Main Spring Boot application entry point with startup logging.',
    content: `package com.devops.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    private static final Logger logger = LoggerFactory.getLogger(Application.class);

    public static void main(String[] args) {
        logger.info("Initializing Java Gradle DevOps Application...");
        SpringApplication.run(Application.class, args);
        logger.info("Java Gradle DevOps Application started successfully on port 8080");
    }
}`
  },
  {
    path: 'src/main/java/com/devops/app/controller/HelloController.java',
    name: 'HelloController.java',
    category: 'source',
    language: 'java',
    description: 'REST Controller serving the GET /api/hello greeting endpoint with logging and parameter support.',
    content: `package com.devops.app.controller;

import com.devops.app.model.ApiResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

    private static final Logger logger = LoggerFactory.getLogger(HelloController.class);

    @Value("\${app.version:1.0.0}")
    private String appVersion;

    @Value("\${app.environment:development}")
    private String appEnvironment;

    @GetMapping("/api/hello")
    public ResponseEntity<ApiResponse> getHello(
            @RequestParam(value = "name", defaultValue = "World") String name) {
        logger.info("Handling GET /api/hello request for name: {}", name);
        String greeting = "Hello, " + name + "! Welcome to the Java Gradle DevOps Application.";
        ApiResponse response = new ApiResponse(greeting, "SUCCESS", appEnvironment, appVersion);
        return ResponseEntity.ok(response);
    }
}`
  },
  {
    path: 'src/main/java/com/devops/app/controller/HealthController.java',
    name: 'HealthController.java',
    category: 'source',
    language: 'java',
    description: 'REST Controller serving GET /health with live JVM runtime statistics, memory, and uptime.',
    content: `package com.devops.app.controller;

import com.devops.app.model.HealthResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.lang.management.ManagementFactory;
import java.util.LinkedHashMap;
import java.util.Map;

@RestController
public class HealthController {

    private static final Logger logger = LoggerFactory.getLogger(HealthController.class);

    @Value("\${spring.application.name:java-gradle-devops}")
    private String appName;

    @Value("\${app.version:1.0.0}")
    private String appVersion;

    @GetMapping("/health")
    public ResponseEntity<HealthResponse> getHealth() {
        logger.debug("Health check probe requested");

        Runtime runtime = Runtime.getRuntime();
        long totalMemory = runtime.totalMemory();
        long freeMemory = runtime.freeMemory();
        long usedMemory = totalMemory - freeMemory;
        long maxMemory = runtime.maxMemory();
        long uptimeMs = ManagementFactory.getRuntimeMXBean().getUptime();

        Map<String, Object> metrics = new LinkedHashMap<>();
        metrics.put("status", "UP");
        metrics.put("uptimeSeconds", uptimeMs / 1000);
        metrics.put("availableProcessors", runtime.availableProcessors());
        metrics.put("usedMemoryMB", usedMemory / (1024 * 1024));
        metrics.put("totalMemoryMB", totalMemory / (1024 * 1024));
        metrics.put("maxMemoryMB", maxMemory / (1024 * 1024));

        HealthResponse response = new HealthResponse("UP", appName, appVersion, metrics);
        return ResponseEntity.ok(response);
    }
}`
  },
  {
    path: 'src/main/java/com/devops/app/model/ApiResponse.java',
    name: 'ApiResponse.java',
    category: 'source',
    language: 'java',
    description: 'Data Transfer Object modeling standardized REST responses.',
    content: `package com.devops.app.model;

import java.time.Instant;

public class ApiResponse {
    private String message;
    private String status;
    private String timestamp;
    private String environment;
    private String version;

    public ApiResponse() {
        this.timestamp = Instant.now().toString();
    }

    public ApiResponse(String message, String status, String environment, String version) {
        this.message = message;
        this.status = status;
        this.timestamp = Instant.now().toString();
        this.environment = environment;
        this.version = version;
    }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }

    public String getEnvironment() { return environment; }
    public void setEnvironment(String environment) { this.environment = environment; }

    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }
}`
  },
  {
    path: 'src/main/java/com/devops/app/model/HealthResponse.java',
    name: 'HealthResponse.java',
    category: 'source',
    language: 'java',
    description: 'Data Transfer Object encapsulating system health status and telemetry metrics.',
    content: `package com.devops.app.model;

import java.time.Instant;
import java.util.Map;

public class HealthResponse {
    private String status;
    private String appName;
    private String version;
    private String timestamp;
    private Map<String, Object> systemMetrics;

    public HealthResponse() {
        this.timestamp = Instant.now().toString();
    }

    public HealthResponse(String status, String appName, String version, Map<String, Object> systemMetrics) {
        this.status = status;
        this.appName = appName;
        this.version = version;
        this.timestamp = Instant.now().toString();
        this.systemMetrics = systemMetrics;
    }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getAppName() { return appName; }
    public void setAppName(String appName) { this.appName = appName; }

    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }

    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }

    public Map<String, Object> getSystemMetrics() { return systemMetrics; }
    public void setSystemMetrics(Map<String, Object> systemMetrics) { this.systemMetrics = systemMetrics; }
}`
  },
  {
    path: 'src/main/java/com/devops/app/exception/GlobalExceptionHandler.java',
    name: 'GlobalExceptionHandler.java',
    category: 'source',
    language: 'java',
    description: 'Centralized exception controller advice intercepting HTTP 400, 404, and 500 errors.',
    content: `package com.devops.app.exception;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.resource.NoResourceFoundException;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

@RestControllerAdvice
public class GlobalExceptionHandler {

    private static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<Map<String, Object>> handleNotFound(NoResourceFoundException ex) {
        logger.warn("Resource not found: {}", ex.getResourcePath());
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("status", HttpStatus.NOT_FOUND.value());
        body.put("error", "Not Found");
        body.put("message", "The requested endpoint does not exist: " + ex.getResourcePath());
        body.put("timestamp", Instant.now().toString());
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(body);
    }

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<Map<String, Object>> handleIllegalArgument(IllegalArgumentException ex) {
        logger.warn("Bad request parameter: {}", ex.getMessage());
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("status", HttpStatus.BAD_REQUEST.value());
        body.put("error", "Bad Request");
        body.put("message", ex.getMessage());
        body.put("timestamp", Instant.now().toString());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(body);
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String, Object>> handleGeneralException(Exception ex) {
        logger.error("Unhandled server exception encountered", ex);
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("status", HttpStatus.INTERNAL_SERVER_ERROR.value());
        body.put("error", "Internal Server Error");
        body.put("message", "An unexpected error occurred while processing the request");
        body.put("timestamp", Instant.now().toString());
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(body);
    }
}`
  },
  {
    path: 'src/main/resources/application.properties',
    name: 'application.properties',
    category: 'source',
    language: 'properties',
    description: 'Spring Boot runtime configuration: port 8080, logging levels, and Actuator endpoints.',
    content: `# Application metadata
spring.application.name=java-gradle-devops
app.version=1.0.0
app.environment=production

# Server configuration
server.port=8080
server.shutdown=graceful

# Logging configuration
logging.level.root=INFO
logging.level.com.devops.app=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Spring Boot Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true`
  },
  {
    path: 'src/test/java/com/devops/app/ApplicationTests.java',
    name: 'ApplicationTests.java',
    category: 'test',
    language: 'java',
    description: 'JUnit 5 integration test validating successful Spring application context initialization.',
    content: `package com.devops.app;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ApplicationTests {

    @Test
    void contextLoads() {
        // Verifies that the Spring Boot ApplicationContext starts without errors
    }
}`
  },
  {
    path: 'src/test/java/com/devops/app/HelloControllerTest.java',
    name: 'HelloControllerTest.java',
    category: 'test',
    language: 'java',
    description: 'MockMvc controller unit test validating /api/hello status code and JSON payload attributes.',
    content: `package com.devops.app;

import com.devops.app.controller.HelloController;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.notNullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(HelloController.class)
class HelloControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    @DisplayName("GET /api/hello should return 200 OK with default greeting")
    void testGetHelloDefault() throws Exception {
        mockMvc.perform(get("/api/hello").accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("SUCCESS"))
                .andExpect(jsonPath("$.message").value(containsString("Hello, World!")))
                .andExpect(jsonPath("$.timestamp").value(notNullValue()))
                .andExpect(jsonPath("$.version").value(notNullValue()));
    }

    @Test
    @DisplayName("GET /api/hello?name=DevOpsEngineer should greet personalized name")
    void testGetHelloCustomName() throws Exception {
        mockMvc.perform(get("/api/hello?name=DevOpsEngineer").accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("SUCCESS"))
                .andExpect(jsonPath("$.message").value(containsString("Hello, DevOpsEngineer!")))
                .andExpect(jsonPath("$.timestamp").value(notNullValue()));
    }
}`
  },
  {
    path: 'src/test/java/com/devops/app/HealthControllerTest.java',
    name: 'HealthControllerTest.java',
    category: 'test',
    language: 'java',
    description: 'MockMvc unit test asserting that /health returns HTTP 200, status UP, and system metrics.',
    content: `package com.devops.app;

import com.devops.app.controller.HealthController;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(HealthController.class)
class HealthControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    @DisplayName("GET /health should return 200 OK with status UP and system metrics")
    void testGetHealthReturnsUp() throws Exception {
        mockMvc.perform(get("/health").accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("UP")))
                .andExpect(jsonPath("$.appName", notNullValue()))
                .andExpect(jsonPath("$.timestamp", notNullValue()))
                .andExpect(jsonPath("$.systemMetrics.status", is("UP")))
                .andExpect(jsonPath("$.systemMetrics.usedMemoryMB", notNullValue()));
    }
}`
  },
  {
    path: 'Dockerfile',
    name: 'Dockerfile',
    category: 'docker',
    language: 'dockerfile',
    description: 'Production multi-stage build: compiles with Eclipse Temurin JDK and runs as non-root user on Temurin JRE.',
    content: `# Multi-stage Dockerfile for Java Gradle DevOps Application
FROM eclipse-temurin:17-jdk-jammy AS builder

WORKDIR /build

# Copy Gradle wrapper and configuration files first to leverage Docker layer caching
COPY gradlew settings.gradle build.gradle ./
COPY gradle/ ./gradle/

# Ensure execution permissions
RUN chmod +x gradlew

# Download dependencies
RUN ./gradlew dependencies --no-daemon || true

# Copy project source code
COPY src/ ./src/

# Compile and package executable bootJar
RUN ./gradlew bootJar --no-daemon

# Runtime Stage
FROM eclipse-temurin:17-jre-jammy AS runner

# Create non-root user
RUN groupadd -r devops && useradd -r -g devops -m -d /app devops
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/build/libs/java-gradle-devops-1.0.0.jar ./app.jar
RUN chown -R devops:devops /app

USER devops:devops
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \\
  CMD wget -qO- http://localhost:8080/health || exit 1

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar app.jar"]`
  },
  {
    path: '.dockerignore',
    name: '.dockerignore',
    category: 'docker',
    language: 'ignore',
    description: 'Excludes local build directories, git history, and temp files from Docker build context.',
    content: `.git
.gitignore
.github
.gradle
build
out
.idea
*.iml
.vscode
*.log
README.md`
  },
  {
    path: '.github/workflows/build.yml',
    name: 'build.yml',
    category: 'ci',
    language: 'yaml',
    description: 'GitHub Actions workflow automating JDK 17 setup, Gradle caching, test execution, and JAR archiving.',
    content: `name: CI Build & Test Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build, Test & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up OpenJDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon

      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-reports
          path: build/reports/tests/test/
          retention-days: 7

      - name: Build Executable Boot JAR
        run: ./gradlew bootJar --no-daemon

      - name: Archive Built Application JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-gradle-devops-jar
          path: build/libs/*.jar
          retention-days: 14

  docker-lint-build:
    name: Verify Docker Container Build
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: java-gradle-devops:ci-check`
  },
  {
    path: '.gitignore',
    name: '.gitignore',
    category: 'doc',
    language: 'ignore',
    description: 'Git ignore rules for Java compiled classes, Gradle build directories, IDE metadata, and logs.',
    content: `*.class
*.log
*.jar
*.war
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar
.idea/
*.iws
*.iml
*.ipr
out/
.vscode/
.DS_Store`
  },
  {
    path: 'README.md',
    name: 'README.md',
    category: 'doc',
    language: 'markdown',
    description: 'Exhaustive project documentation covering architecture, Gradle explanation, Windows PowerShell commands, Docker, and CI/CD.',
    content: `# Java Gradle DevOps Application

A production-ready, beginner-friendly DevOps reference application built with Java 17 and Spring Boot 3. It demonstrates industry-standard development and operations practices: automated dependency management with Gradle, robust RESTful APIs with centralized error handling, unit testing with JUnit 5, containerization with Docker multi-stage builds, and continuous integration with GitHub Actions.

---

## Table of Contents
1. [Project Overview](#project-overview)
2. [Architecture](#architecture)
3. [Technologies](#technologies)
4. [Project Structure](#project-structure)
5. [Understanding Gradle](#understanding-gradle)
   - [What Gradle Is](#what-gradle-is)
   - [How Gradle Dependencies Work](#how-gradle-dependencies-work)
6. [Windows PowerShell Quick Commands](#windows-powershell-quick-commands)
7. [Step-by-Step Developer Guide](#step-by-step-developer-guide)
   - [1. Check Java Environment](#1-check-java-environment)
   - [2. Build using Gradle Wrapper](#2-build-using-gradle-wrapper)
   - [3. Run Tests](#3-run-tests)
   - [4. Start the Application](#4-start-the-application)
   - [5. Test the REST APIs](#5-test-the-rest-apis)
   - [6. Create and Run the Executable JAR](#6-create-and-run-the-executable-jar)
8. [Docker Containerization](#docker-containerization)
   - [Build the Docker Image](#build-the-docker-image)
   - [Run the Docker Container](#run-the-docker-container)
   - [Check Status and Logs](#check-status-and-logs)
   - [Stop and Clean Up](#stop-and-clean-up)
9. [GitHub Actions CI/CD Pipeline](#github-actions-cicd-pipeline)
10. [Common Troubleshooting](#common-troubleshooting)

---

## Windows PowerShell Quick Commands

1. Check Java:
   java -version

2. Build using Gradle Wrapper:
   .\\gradlew.bat build

3. Run tests:
   .\\gradlew.bat test

4. Start the application:
   .\\gradlew.bat bootRun

5. Test the API:
   Invoke-RestMethod -Uri "http://localhost:8080/api/hello?name=Developer"
   Invoke-RestMethod -Uri "http://localhost:8080/health"

6. Create the JAR:
   .\\gradlew.bat bootJar

7. Run the JAR:
   java -jar build/libs/java-gradle-devops-1.0.0.jar

8. Build Docker image:
   docker build -t java-gradle-devops:latest .

9. Run Docker container:
   docker run -d --name java-devops-container -p 8080:8080 java-gradle-devops:latest

10. Check Docker status:
    docker ps --filter "name=java-devops-container"

11. View Docker logs:
    docker logs -f java-devops-container

12. Stop the container:
    docker stop java-devops-container
    docker rm java-devops-container`
  }
];
